### ISSUE TITLE
Is it possible to use audio>10 seconds for training/inference?

### ISSUE THREAD

**Issue by yukiarimo** [RVC-Boss/GPT-SoVITS#1780]
Hello. Is it possible to train (using the official google colab) the GPT-SoVITS-V2 with audios longer than 10 seconds, not splitting them?

Also, what about inference? Why it is limited to `3<audio<10`?

**Comment by XXXXRT666** [comment]
1. Yes, there is a limit in config file
2. AR is not stable for long semantic or short semantic

**Comment by yukiarimo** [comment]
1. Can you please show where it is (that config file) so I can modify it?
2. What does AR stand for? And why it is not stable (just curious, cause the generation itself seems somewhat stable for the long sequences)?

**Comment by XXXXRT666** [comment]
1. `GPT_SoVITS/configs/s1longer-v2.yaml` max_sec
2. Autoregressive. Error Accumulation & sensitivity to Input Noise, it's a strong sequence dependency progress

**Comment by yukiarimo** [comment]
Thank you, I’ll try! In the google colab do I need to additionally configure something or just change the parameters in the config file? Also, can you please explain some of these parameters in the config?

```
train:
  seed: 1234
  epochs: 20
  batch_size: 8
  save_every_n_epoch: 1
  precision: 16-mixed
  gradient_clip: 1.0
optimizer:
  lr: 0.01
  lr_init: 0.00001
  lr_end: 0.0001
  warmup_steps: 2000
  decay_steps: 40000
data:
  max_eval_sample: 8
  max_sec: 54
  num_workers: 4
  pad_val: 1024 # same with EOS in model
```

By the way, do I need to fine-tune two other models (the last two) are what are they responsible for?

```
from gpt_sovits import TTS, TTS_Config

soviets_configs = {
    "default": {
        "device": "cuda",  #  ["cpu", "cuda"]
        "is_half": True,  #  Set 'False' if you will use cpu
        "t2s_weights_path": "pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt", # gpt model
        "vits_weights_path": "pretrained_models/s2G488k.pth",
        "cnhuhbert_base_path": "pretrained_models/chinese-hubert-base",
        "bert_base_path": "pretrained_models/chinese-roberta-wwm-ext-large"
    }
}

tts_config = TTS_Config(soviets_configs)
```
