### ISSUE TITLE
[教程] 基于docker compose部署的GPT-SoVITs实现OpenAI API的方法

### ISSUE THREAD

**Issue by WiiGe** [RVC-Boss/GPT-SoVITS#2195]
## 摘要

本文旨在结合 [`GPT-sovits-2-OpenAI`](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main) 项目和 [`GPT-SoVITS`](https://github.com/RVC-Boss/GPT-SoVITS/tree/main) 项目, 实现一种将 [`GPT-SoVITS`](https://github.com/RVC-Boss/GPT-SoVITS/tree/main) 包装为符合 [`OpenAI Audio API`](https://platform.openai.com/docs/api-reference/audio) 格式的零成本方案, 以便接入各类LLM推理界面, 弥补 [GPT-SoVITS指南](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e) 中的不全面之处, 如有错漏, 欢迎在下方指出, 见后定将尽快修正.

## TL;DR

将 `GPT-SoVITS API` 转换为 [`OpenAI Audio API`](https://platform.openai.com/docs/api-reference/audio) 只需三步:

### 准备`tts-adapter`的配置文件

将以下两个配置文件放到`docker-compose.yaml`的同级目录中

1. 服务环境文件 `tts-adapter.env`: 
    ```
    # Backend URL
    BACKEND_URL=http://<你的GPT-SoVITS服务IP地址>:9880
    # OPenAI API 的Key
    API_KEY='!QmCvfKi9wUyusaEeuPBCDG7Ho%dtWXc'
    # generation parameters
    # TEXT_LANGUAGE=zh
    # TOP_K=15 
    # TOP_P=1
    # TEMPERATURE=0.45
    # SPEED=0.95
    ```
2. 接口配置文件 `tts-adapter-config.yaml`: 
    ```
    voices:
        # OpenAI API中的voice参数, 此处为`ruan_mei`
        ruan_mei:
            models:
            # GPT模型目录位置
            gpt_model_path: "GPT_weights/阮•梅-e10.ckpt"
            # SoVITS模型目录位置
            sovits_model_path: "SoVITS_weights/阮•梅_e15_s495.pth"
            refer:
            #参考音频文件目录位置
            refer_wav_path: "reference/sample.wav"
            #参考音频的文本内容
            prompt_text: "我叫阮•梅，念我名字时，请别忘了中间气息的停歇。"
        # 使用Windows路径的第二个声音配置
        # echo:
        #   models:
        #     gpt_model_path: "F:/model3"
        #     sovits_model_path: "F:/model4"
        #   refer:
        #     refer_wav_path: "F:/2.wav"
        #     prompt_text: "text_here"
    ```

### 启动 `OpenAI Audio API`

将GPT-SoVITS的官方 `docker-compose.yaml` 文件修改为: 
```
# https://github.com/RVC-Boss/GPT-SoVITS/tree/main
services:
  gpt-sovits:
    image: breakstring/gpt-sovits:latest
    # 该容器的名称
    container_name: gpt-sovits
    environment:
      # 启用半精度推理, 根据实际情况调整
      - is_half=True
      - is_share=False
    # 启动API， 默认为api.py, docker镜像中并不存在api_v2.py这一文件, 该文件就是v3的API
    command:
      - python
      - api.py
    volumes:
      - ./output:/workspace/output
      - ./logs:/workspace/logs
      - ./SoVITS_weights:/workspace/SoVITS_weights
      - ./GPT_weights:/workspace/GPT_weights
      - ./reference:/workspace/reference
      - ./models/asr:/workspace/tools/asr/models
      - ./models/G2PWModel:/workspace/GPT_SoVITS/text/G2PWModel
      - ./models/pretrained_models/s2Gv3.pth:/workspace/GPT_SoVITS/pretrained_models/s2Gv3.pth
    working_dir: /workspace
    ports:
      # API 端口
      - "9880:9880"
      # 校对工具端口
      - "9871:9871"
      # 推理界面端口
      - "9872:9872"
      # UVR5界面端口
      - "9873:9873"
      # 主界面端口
      - "9874:9874"
    # YMMV, 根据实际情况调整
    shm_size: 32G
    # 同样YMMV, 根据实际情况调整
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - GPT_SoVITS_App
  tts-adapter-service:
    image: austinleo/tts-adapter:latest
    # 该容器的名称
    container_name: gpt-sovits-tts-adapter
    # OpenAI API端口, 根据实际情况调整
    ports:
      - "5000:5000"
    # 上一步中准备好的服务环境文件
    env_file:
      - tts-adapter.env
    restart: always
    networks:
      - GPT_SoVITS_App
    volumes:
      # 上一步中准备好的声音配置文件
      - ./tts-adapter-config.yaml:/app/config.yaml 
networks:
  # 两个容器合并到同一个桥接网络 GPT_SoVITS_App 上, 以便互相通信
  GPT_SoVITS_App:
    external: true
```

更新该文件后, 执行该命令创建桥接网络 `GPT_SoVITS_App`: `sudo docker network create GPT_SoVITS_App`.

然后在同目录下执行: `sudo docker compose -f docker-compose.yaml up -d` 其可以Docker方式启动API, 其访问端点为: `http://<你的GPT-SoVITS服务IP地址>:5000/v1/audio/speech`.

如果没有在文件中更改容器名称的话, 可以用 `sudo docker logs -f gpt-sovits` 和 `sudo docker logs -f gpt-sovits-tts-adapter` 分别监控其终端输出, 查看是否有配置错误导致的报错.

### 接入LLM WebUI(以 `OpenWebUI` 为例)

在 `OpenWebUI` 中选择 `管理员面板 -> 设置 -> 语音` 页面中, 将:
- `文本转语音引擎` 设置为 `OpenAI`
- `文本转语音引擎地址` 设置为 `http://<你的GPT-SoVITS服务IP地址>:5000` (匹配 `docker-compose.yaml` 中的配置)
- `文本转语音引擎API-Key` 设置为 `!QmCvfKi9wUyusaEeuPBCDG7Ho%dtWXc` (匹配 `tts-adapter-config.yaml` 中的配置)
- `文本转语音音色` 设置为 `ruan_mei` (匹配 `tts-adapter-config.yaml` 中的配置)
- `文本转语音模型` 留空

配置完成, 现在 `OpenWebUI` 将使用 `GPT-SoVITS` 合成LLM的回复语音.

## 现有接口的问题

[`GPT-SoVITS指南`](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e) 中并没有任何提及API或是其使用的相关条目, 或因正在积极开发中, API的相关信息均包含在源码 [GPT-SoVITS/GPT-SoVITS/api.py](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/api.py) 的注释之中. 
其格式为(以GET方法为例): `http://127.0.0.1:9880?refer_wav_path=123.wav&prompt_text=一二三。&prompt_language=zh&text=先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。&text_language=zh&top_k=20&top_p=0.6&temperature=0.6&speed=1&inp_refs="456.wav"&inp_refs="789.wav"` ,其中:

- 参考音频文件: 123.wav
- 参考音频内容: 一二三
- 参考音频语言: zh
- 输入文本: 先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。
- 输入文本语言: zh
- top_k: 20
- top_p: 0.6
- temperature: 0.6
- 生成语音的谈话速度: 1
- inp_refs: 456.wav和789.wav

该格式与大部分使用 [Openai API Audio](https://platform.openai.com/docs/api-reference/audio) 格式API的热门应用显然无法兼容:

```
curl https://api.openai.com/v1/audio/speech \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "alloy"
  }' \
  --output speech.mp3
```

因此需要某种包装器将该API包装为其他应用可以识别的 [Openai API Audio](https://platform.openai.com/docs/api-reference/audio) 格式API.

## 示例环境

本文中的示例操作系统为`Ubuntu 24 LTS Server`: 

```
$ uname -a
Linux hp-z8g5 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
```

本文所用示例模型: [baicai1145/GPT-SoVITS-STAR](https://huggingface.co/baicai1145/GPT-SoVITS-STAR/tree/main)

Web服务器及Python版本: `Werkzeug/3.0.6 Python/3.10.15`

本文中涉及的Docker镜像, 镜像标签均使用`latest`:
- [breakstring/gpt-sovits](https://hub.docker.com/r/breakstring/gpt-sovits)
- [austinleo/tts-adapter](https://hub.docker.com/r/austinleo/tts-adapter)

## 本文的目标读者

* 了解Linux基本使用方式的用户
* 通过[Docker Compose](https://docs.docker.com/compose/)使用[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS/tree/main)的用户
* 希望将[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS/tree/main)集成到[OpenWebUI](https://github.com/open-webui/open-webui)或其他使用兼容OpenAI API的LLM推理UI的用户

## 实现原理&步骤

通过启动一个 [Flask](https://flask.palletsprojects.com/en/stable/) 服务, 接受 [`OpenAI Audio API`](https://platform.openai.com/docs/api-reference/audio) 格式的请求, 解析后转发给作为后端的 `GPT-SoVITS API` 服务. 音频文件生成完成后沿原请求路径反向发回请求方. 因此对需要使用TTS的LLM界面来说, 整个服务看上去就是一个 `OpenAI API` 端点, [`GPT-SoVITS`](https://github.com/RVC-Boss/GPT-SoVITS/tree/main)对其完全透明, 因此可将 [GPT-sovits-2-OpenAI](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main) 视为是 [`GPT-SoVITS`](https://github.com/RVC-Boss/GPT-SoVITS/tree/main) 的OpenAI API包装器. 

### 项目目录结构

本文所用示例的目录结构为:

```
$ tree
./
├── GPT_weights
├── logs
├── models
│   ├── asr
│   ├── G2PWModel
│   └── pretrained_models
├── output
│   ├── asr_opt
│   ├── denoise_opt
│   ├── slicer_opt
│   └── uvr5_opt
├── reference
└── SoVITS_weights
```

- `GPT_weights`: GPT模型所在目录
- `SoVITS_weights` : SoVITS模型所在目录
- `output`: 训练过程的中间文件所在目录
- `reference`: 参考音频所在目录
- `models`: ASR, G2PW 预训练模型所在目录
- `logs`: 模型训练的日志缓存等文件所在目录

#### 本文中的关键文件位置:

- GPT模型 : `GPT_weights/阮•梅-e10.ckpt`
- SoVITS模型 : `SoVITS_weights/阮•梅_e15_s495.pth`
- docker-compose启动文件`docker-compose.yaml` : `./docker-compose.yaml` (即位于项目根目录)
- 参考音频: `reference/sample.wav` (其内容为: `我叫阮•梅，念我名字时，请别忘了中间气息的停歇。`)
- 服务环境文件 `tts-adapter.env`: `./tts-adapter.env` (即位于项目根目录)
- 接口配置文件 `tts-adapter-config.yaml`: `./tts-adapter-config.yaml` (即位于项目根目录)

### 将以API模式启动GPT-SoVITS Docker容器

通过源码注释中给出的 `python api.py -dr "123.wav" -dt "一二三。" -dl "zh"` 命令来启动`GPT-SoVITS` API 仅适用于使用整合包部署服务的用户, 因为[Docker Compose](https://docs.docker.com/compose/)无法直接执行python命令, 然而[GPT-SoVITS指南](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)中仍未提及相关实践. 不过在[【語音合成技術 - GPT-SoVITS】如何架設API伺服器](https://vocus.cc/article/67295e9bfd89780001cfc098)这篇博文中给出了一个很好的示例, 只需将文章中对 `docker-compose.yaml` 的修改:

```
command:
  - python
  - api_v3.py
```

调整为:

```
command:
  - python
  - api.py
```

即可. 因为官方镜像中并不存在 `api_v2.py`, 所以在不额外挂载代码文件的情况下, 并没有手段启动v2版的API.

这一修改本质上是用 `python api.py` 覆盖了容器镜像中的默认命令, 可见文档[Dockers Compose - Services top-level elements](https://docs.docker.com/reference/compose-file/services/#command).

### 准备tts-adapter配置文件

将以下两个配置文件放到`docker-compose.yaml`旁边:

1. 服务环境文件 `tts-adapter.env`: 
    ```
    # Backend URL
    BACKEND_URL=http://<你的GPT-SoVITS服务IP地址>:9880
    # OPenAI API 的Key
    API_KEY='!QmCvfKi9wUyusaEeuPBCDG7Ho%dtWXc'
    # generation parameters
    # TEXT_LANGUAGE=zh
    # TOP_K=15 
    # TOP_P=1
    # TEMPERATURE=0.45
    # SPEED=0.95
    ```
2. 接口配置文件 `tts-adapter-config.yaml`: 
    ```
    voices:
        # OpenAI API中的voice参数, 此处为`ruan_mei`
        ruan_mei:
            models:
            # GPT模型目录位置
            gpt_model_path: "GPT_weights/阮•梅-e10.ckpt"
            # SoVITS模型目录位置
            sovits_model_path: "SoVITS_weights/阮•梅_e15_s495.pth"
            refer:
            #参考音频文件目录位置
            refer_wav_path: "reference/sample.wav"
            #参考音频的文本内容
            prompt_text: "我叫阮•梅，念我名字时，请别忘了中间气息的停歇。"
        # 使用Windows路径的第二个声音配置
        # echo:
        #   models:
        #     gpt_model_path: "F:/model3"
        #     sovits_model_path: "F:/model4"
        #   refer:
        #     refer_wav_path: "F:/2.wav"
        #     prompt_text: "text_here"
    ```

务必根据实际情况修改带有注释的内容

### 启动tts-adapter以实现OpenAI API

新建一个 `tts-adapter-docker-compose.yaml` 文件:

```
tts-adapter-service:
  image: austinleo/tts-adapter:latest
  container_name: gpt-sovits-tts-adapter
  ports:
    - "9850:5000"
  env_file:
    - tts-adapter.env
  restart: always
  networks:
    - Apps
  volumes:
    - ./tts-adapter-config.yaml:/app/config.yaml 
```
确认tts-adapter(即[GPT-sovits-2-OpenAI](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main))的配置文件无误后, 使用 `sudo docker compose -f tts-adapter-docker-compose.yaml up -d` 启动OpenAI API.

### 接入LLM WebUI(以 `OpenWebUI` 为例)

在 `OpenWebUI` 中选择 `管理员面板 -> 设置 -> 语音` 页面中, 将:
- `文本转语音引擎` 设置为 `OpenAI`
- `文本转语音引擎地址` 设置为 `http://<你的GPT-SoVITS服务IP地址>:5000` (匹配 `docker-compose.yaml` 中的配置)
- `文本转语音引擎API-Key` 设置为 `!QmCvfKi9wUyusaEeuPBCDG7Ho%dtWXc` (匹配 `tts-adapter-config.yaml` 中的配置)
- `文本转语音音色` 设置为 `ruan_mei` (匹配 `tts-adapter-config.yaml` 中的配置)
- `文本转语音模型` 留空

现在 `OpenWebUI` 就可以使用 `GPT-SoVITS` 合成LLM的回复语音了.

### 验证服务可用性

使用 `curl`:
```
curl http://<你的GPT-SoVITS服务IP地址>:<你设置的GPT-sovits-2-OpenAI端口号>/v1/audio/speech \
  -H "Authorization: Bearer <你设置的API-KEY>" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "<输入文本>",
    "voice": "<音色名称>",
    "response_format": "wav",
    "speed": 1.0
  }'  \
  --output speech.mp3
```

示例: 
```
curl http://192.168.50.150:5000/v1/audio/speech \
  -H "Authorization: Bearer !QmCvfKi9wUyusaEeuPBCDG7Ho%dtWXc" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "我不明白，为什么大家都在谈论着项羽被困垓下，仿佛这中原古战场，对于我们注定了凶多吉少。二十年前，我从徐州踏上征途，开始了第二次北伐，中华秋海棠叶遂归于一统。本党本军所到之处，民众竭诚欢迎，真可谓占尽天时。那种勃勃生机、万物竞发的境界，犹在眼前。短短二十年之后，这里竟至于一变而成为我的葬身之地了么？无论怎么讲，会战兵力是八十万对六十万，优势在我!",
    "voice": "ruan_mei",
    "response_format": "wav",
    "speed": 1.0
  }'  \
  --output retard_Chiang_Kai_shek_奉化口音.mp3
```

也可以使用常见的浏览器API测试工具:

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/5c3d1fd5-b864-40fc-a8b8-a28220d646e8" />

### (可选)合并为一个Docker容器堆栈

将[GPT-sovits-2-OpenAI](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main)和[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS)合并为一个容器堆栈, 通过 `sudo docker compose -f docker-compose.yaml up -d` 一键启动所有服务无疑是令人舒适的. 要实现这样的效果, 只需简单地将[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS)项目中提供的 [`docker-compose.yaml`](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/docker-compose.yaml) 文件修改为: 
```
# https://github.com/RVC-Boss/GPT-SoVITS/tree/main
services:
  gpt-sovits:
    image: breakstring/gpt-sovits:latest
    # 该容器的名称
    container_name: gpt-sovits
    environment:
      # 启用半精度推理, 根据实际情况调整
      - is_half=True
      - is_share=False
    # 启动API， 默认为api.py, docker镜像中并不存在api_v2.py这一文件, 该文件就是v3的API
    command:
      - python
      - api.py
    volumes:
      - ./output:/workspace/output
      - ./logs:/workspace/logs
      - ./SoVITS_weights:/workspace/SoVITS_weights
      - ./GPT_weights:/workspace/GPT_weights
      - ./reference:/workspace/reference
      - ./models/asr:/workspace/tools/asr/models
      - ./models/G2PWModel:/workspace/GPT_SoVITS/text/G2PWModel
      - ./models/pretrained_models/s2Gv3.pth:/workspace/GPT_SoVITS/pretrained_models/s2Gv3.pth
    working_dir: /workspace
    ports:
      # API 端口
      - "9880:9880"
      # 校对工具端口
      - "9871:9871"
      # 推理界面端口
      - "9872:9872"
      # UVR5界面端口
      - "9873:9873"
      # 主界面端口
      - "9874:9874"
    # YMMV, 根据实际情况调整
    shm_size: 32G
    # 同样YMMV, 根据实际情况调整
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - GPT_SoVITS_App
  tts-adapter-service:
    image: austinleo/tts-adapter:latest
    # 该容器的名称
    container_name: gpt-sovits-tts-adapter
    # OpenAI API端口, 根据实际情况调整
    ports:
      - "5000:5000"
    # 上一步中准备好的服务环境文件
    env_file:
      - tts-adapter.env
    restart: always
    networks:
      - GPT_SoVITS_App
    volumes:
      # 上一步中准备好的声音配置文件
      - ./tts-adapter-config.yaml:/app/config.yaml 
networks:
  # 两个容器合并到同一个桥接网络 GPT_SoVITS_App 上, 以便互相通信
  GPT_SoVITS_App:
    external: true
```

更新该文件后, 执行该命令创建桥接网络 `GPT_SoVITS_App`: `sudo docker network create GPT_SoVITS_App`.

然后在同目录下执行: `sudo docker compose -f docker-compose.yaml up -d` 其可以Docker方式启动API, 其访问端点为: `http://<你的GPT-SoVITS服务IP地址>:5000/v1/audio/speech`.

如果没有在文件中更改容器名称的话, 可以用 `sudo docker logs -f gpt-sovits` 和 `sudo docker logs -f gpt-sovits-tts-adapter` 分别监控其终端输出, 查看是否有配置错误导致的报错.

## 注意事项

- 习惯直接使用docker命令建立容器的用户, 请使用[decomposerize](https://www.decomposerize.com/)自行将docker-compose.yaml文件转为docker命令
- 如果不希望手动创建Docker桥接网络 `GPT_SoVITS_App`, 也可以按照 [GPT-sovits-2-OpenAI/.env.example](https://github.com/RedwindA/GPT-sovits-2-OpenAI/blob/main/.env.example)中所述, 使用 `http://host.docker.internal:9880` 来实现容器间通信

## 已知问题

- 不支持流式GPT-SoVITs接口, 见[GPT-sovits-2-OpenAI](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main#未来开发计划)
- 不支持指定切分参数
- 不支持v2版API

## 参考文献&资料

- [【語音合成技術 - GPT-SoVITS】如何架設API伺服器](https://vocus.cc/article/67295e9bfd89780001cfc098)
- [GPT-SoVITS指南](https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e)
- [GPT-sovits-2-OpenAI](https://github.com/RedwindA/GPT-sovits-2-OpenAI/tree/main)
- [GPT-SoVITS/docker-compose.yaml](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/docker-compose.yaml)
- [GPT-SoVITS/GPT-SoVITS/api.py](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/api.py)
- [baicai1145/GPT-SoVITS-STAR](https://huggingface.co/baicai1145/GPT-SoVITS-STAR/tree/main)
- [GPT-SoVITS官方网盘](https://pan.ai-hobbyist.com/Genshin%20Datasets)
- [Openai API Audio Reference](https://platform.openai.com/docs/api-reference/audio)
