### ISSUE TITLE
使用Docker时，无法使用v3版本原因及解决方法

### ISSUE THREAD

**Issue by leeyeel** [RVC-Boss/GPT-SoVITS#2216]
由于[Docker Hub](https://hub.docker.com/r/breakstring/gpt-sovits) 已经长期不更新，导致按照目前的docker-compose.yaml文件拉取下来的镜像，还处于v1版本，而不是v3版。

解决方法是自己本地打包，不使用[Docker Hub](https://hub.docker.com/r/breakstring/gpt-sovits) 中的镜像。
修改docker-compose.yaml文件，添加`build: .`， 即使用本地编译镜像，而不是从远程仓库拉取。

```
version: '3.8'

services:
  gpt-sovits:
    build: .
    image: breakstring/gpt-sovits:latest   # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    container_name: gpt-sovits-container

```
